name: Hello Workflow

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Print date and time
        run: date

      - name: Print branch name
        run: echo "Branch: ${{ github.ref_name }}"name: Hello World
 
jobs:
  test:
    runs-on: self-hosted # ← במקום ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello from my VM
        run: |
          echo "Running on my own server!"
          hostname
          whoami
